ANDROID: mld: fix pragma usage with gcc
Use the recently added pragma only when compiling with clang, otherwise
the build breaks as reported by kernelci:

  drivers/net/wireless/intel/iwlwifi/mld/d3.c:1759: error: ignoring ‘#pragma clang loop’ [-Werror=unknown-pragmas]
   1759 | #pragma clang loop unroll(disable)
        |

Cc: Todd Kjos <tkjos@google.com>
Cc: Lee Jones <joneslee@google.com>
Fixes: 5737edf385416 ("ANDROID: mld: temporary workaround to fortify break")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:f8504377b23bbd100dea49e0f68cf83014967f25
Change-Id: Ia311b7754821ca69f0ce3ee58a507126ad2491db
Signed-off-by: Carlos Llamas <cmllamas@google.com>